

version: '3.8'
# Cada serviço é um container presente na aplicação
services:
  pythonapp:
    build: ./src/ # exucutar a aplicação
    command: sh -c "sleep 20s; python3 ./utils.py" #caminho do código-fonte e 20s para executar o script
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13
    restart: always # Conteiner sempre reiniciado em caso de falha
    environment: 
      POSTGRES_HOST: DB_HOST
      POSTGRES_DB: DB_NAME
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASS
    ports:
      - 'DB_PORT' 
